{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "xo-rps.apiName" . }}-secrets
  labels:
    {{- include "xo-rps.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "xo-rps.apiName" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.sessionSecretKey }}
        property: SESSION_SECRET
{{- end }}
