{{- if .Values.serviceAccount.web.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xo-rps.webName" . }}
  labels:
    {{- include "xo-rps.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.serviceAccount.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xo-rps.apiName" . }}
  labels:
    {{- include "xo-rps.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
