apiVersion: v1
kind: Service
metadata:
  name: {{ include "xo-rps.webName" . }}
  labels:
    {{- include "xo-rps.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "xo-rps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
